# Generated by Django 2.0.1 on 2020-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinduoduo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('rds_public', models.CharField(max_length=100)),
                ('rds_inet', models.CharField(max_length=100)),
                ('rds_pass', models.CharField(max_length=100)),
                ('collector_inet_ip', models.CharField(max_length=100)),
                ('collector_public_ip', models.CharField(max_length=100)),
                ('cloud_inet_ip', models.CharField(max_length=100)),
                ('cloud_public_ip', models.CharField(max_length=100)),
                ('cloud_key', models.CharField(max_length=100)),
                ('auu_key', models.CharField(max_length=100)),
                ('dfg_key', models.CharField(max_length=100)),
                ('baidu_ak', models.CharField(max_length=100)),
                ('baidu_serviceid', models.CharField(max_length=100)),
                ('ptname', models.CharField(max_length=100)),
                ('aesencode', models.CharField(max_length=100)),
            ],
        ),
    ]
